[package]
name = "compression-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
lz4 = "1.23.1"
zstd = "0.12"
sha2 = "0.10.6"
